### ISSUE TITLE
Solr port issue

### ISSUE THREAD

**Issue by hkir-dev** [OBASKTools/pipeline-updatesolr#4]
While running the [whbo OBASK pipeline](https://github.com/hkir-dev/whbo_pipeline) I get error:
```
Initializing schema for ontology collection in server solr:8983
Updating ontology in server solr:8983
Adding texEdge field type
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 31  2682    0     0  100   832      0  38636 --:--:-- --:--:-- --:--:-- 39619
curl: (22) The requested URL returned error: 400
```

But the Solr service is running at port 8993
```yaml
  solr:
    image: solr:8.11
    container_name: solr
    ports:
     - 8993:8983
```
